# This is a basic workflow to help you get started with Actions

name: DocFX

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

jobs:
  generate_and_publish_docs:
    runs-on: ubuntu-latest
    name: Generate and publish the docs
    steps:
    - name: Chekout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - run: dotnet tool update -g docfx
    - run: docfx docfx_project/docfx.json
    - run: ls -lR
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: ./docfx_project/_site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
